### PR TITLE
Update reqwest and add async support

### LINKED ISSUE #18: Use reqwest 0.10
Reqwest has been updated to 0.10 to include `async`/`await` support.

Currently `ApiClient::new()` requires a `reqwest::client::Client`, but as of Reqwest 0.10 the Client import path has changed to `reqwest::async_impl::client::Client`. Since a `Client` must be created and passed in to `new()`, it requires that my binary imports `reqwest = "0.9"` if I want to use this crate.

### PR DESCRIPTION
**Pull request by belak**
This should fix #18 and add support for async. Note that this is a breaking change so a version bump will be necessary.

### CODE REVIEW

**Comment by jgrillo** [comment]
Thank you @belak! I will try to look at these changes this evening EST. This week has been a little wild for me so far.

**Comment by belak** [comment]
Just wanted to check in on this and see if you had the time to take a look. No worries if you don’t have the time right now, just a gentle reminder.

**Comment by jgrillo** [comment]
Hi @belak I have started checking this out , this week has been completely crazy sorry for the delay. I am running into this issue when I try to build your branch: ```
[jgrillo@t460p forecast-rs]$ cargo test
   Compiling reqwest v0.10.4
error: cannot find macro `log_enabled` in this scope
   --> /home/jgrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.4/src/proxy.rs:600:12
    |
600 |         if log::log_enabled!(log::Level::Warn) {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: cannot find macro `log_enabled` in this scope
   --> /home/jgrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.4/src/connect.rs:964:26
    |
964 |             if self.0 && log::log_enabled!(log::Level::Trace) {
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 2 previous errors

error: could not compile `reqwest`.

To learn more, run the command again with --verbose.
```
It looks like reqwest 0.10.4 is failing to build in my environment: ```
[jgrillo@t460p forecast-rs]$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/jgrillo/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.42.0 (b8cedc004 2020-03-09)
```
Do you have any insight into what might be causing this? I thought this was one of the things that the 2018 edition addressed.

**Comment by belak** [comment]
That's really strange... this is the output for me:

```
~/C/forecast-rs % rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/belak/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.42.0 (b8cedc004 2020-03-09)
~/C/forecast-rs % cargo test
   Compiling forecast v2.0.0 (/home/belak/Code/forecast-rs)
warning: unused import: `std::time::Duration`
  --> tests/integration_test.rs:17:5
   |
17 | use std::time::Duration;
   |     ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `Client`, `StatusCode`
  --> tests/integration_test.rs:19:15
   |
19 | use reqwest::{Client, StatusCode};
   |               ^^^^^^  ^^^^^^^^^^

warning: unused imports: `ApiClient`, `ExcludeBlock`, `ExtendBy`, `ForecastRequestBuilder`, `Lang`, `TimeMachineRequestBuilder`, `Units`
  --> tests/integration_test.rs:21:29
   |
21 | use forecast::{ApiResponse, ApiClient, ForecastRequestBuilder,
   |                             ^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^
22 |                TimeMachineRequestBuilder, ExcludeBlock, ExtendBy,
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^^^
23 |                Lang, Units};
   |                ^^^^  ^^^^^

warning: constant item is never used: `LAT`
  --> tests/integration_test.rs:27:1
   |
27 | const LAT: f64 = 42.3736;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: constant item is never used: `LONG`
  --> tests/integration_test.rs:28:1
   |
28 | const LONG: f64 = -71.1097;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant item is never used: `TIME`
  --> tests/integration_test.rs:29:1
   |
29 | const TIME: u64 = 1505899999;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant item is never used: `TIMEOUT_SECS`
  --> tests/integration_test.rs:31:1
   |
31 | const TIMEOUT_SECS: u64 = 60;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished test [unoptimized + debuginfo] target(s) in 2.07s
     Running target/debug/deps/forecast-e6c86f35913a7dca

running 7 tests
test tests::test_norwegian_lang_serde ... ok
test tests::test_forecast_request_builder_defaults ... ok
test tests::test_forecast_request_builder_simple ... ok
test tests::test_forecast_request_builder_complex ... ok
test tests::test_time_machine_request_builder_complex ... ok
test tests::test_time_machine_request_builder_defaults ... ok
test tests::test_time_machine_request_builder_simple ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integration_test-f6729848111d9955

running 2 tests
test test_response_serde_01_21_2018 ... ok
test test_response_serde_10_23_2016 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests forecast

running 1 test
test src/lib.rs -  (line 45) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

~/C/forecast-rs % export FORECAST_API_KEY=<redacted>
~/C/forecast-rs % cargo test --features=integration
   Compiling forecast v2.0.0 (/home/belak/Code/forecast-rs)
    Finished test [unoptimized + debuginfo] target(s) in 6.50s
     Running target/debug/deps/forecast-87f705e975f8c721

running 7 tests
test tests::test_norwegian_lang_serde ... ok
test tests::test_forecast_request_builder_defaults ... ok
test tests::test_forecast_request_builder_complex ... ok
test tests::test_forecast_request_builder_simple ... ok
test tests::test_time_machine_request_builder_complex ... ok
test tests::test_time_machine_request_builder_simple ... ok
test tests::test_time_machine_request_builder_defaults ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integration_test-aa95f839b1539b34

running 8 tests
test test_get_time_machine_request_default ... ok
test test_get_forecast_request_default ... ok
test test_get_forecast_request_full ... ok
test test_get_forecast_request_full_asref ... ok
test test_response_serde_01_21_2018 ... ok
test test_response_serde_10_23_2016 ... ok
test test_get_time_machine_request_default_asref ... ok
test test_get_time_machine_request_full ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests forecast

running 1 test
test src/lib.rs -  (line 45) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by belak** [comment]
As far as I'm aware, that is one of the things fixed by the 2018 edition... I'm not sure why it would be doing that.

**Comment by belak** [comment]
It looks like there was an issue up through log 0.4.5 where that macro wasn't properly exported for use without macro_use (https://github.com/rust-lang/log/issues/300). Maybe we need to make sure we're using a version of log that's semver compatible with 0.4.5 rather than just 0.4. You may have an older version installed (as libraries aren't recommended to commit cargo.lock).

**Comment by jgrillo** [comment]
@belak thanks for tracking this down, I'll try to give it a look tonight.

**Comment by jgrillo** [comment]
@belak it looks like a `cargo update` fixed my issue. Thanks for doing the legwork on that. I didn't get a chance to go over this the other night, I will do my best to get to it ASAP and cut a release by the end of this week.

**Pull request merged**
