### PR TITLE
Update deps, comply with API changes, bump crate version

### PR DESCRIPTION
**Pull request by ParadoxSpiral**
Title, is there any reason this crate is not 1.0?

Edit: There have been some new additions to the API response, will update this PR in a bit.
Edit2: Updated

### CODE REVIEW

**Comment by ParadoxSpiral** [comment]
Weird failures. A rerun will probably fix them?

**Comment by jgrillo** [comment]
Hey @ParadoxSpiral, my apologies! For some reason I didn't get an email notification about this PR, and since this isn't the github account I've been using for work I didn't notice this until now :/. It's getting late here, l'll take a look at your changes tomorrow morning.

**Comment by jgrillo** [comment]
The integration tests are failing due to security restrictions in TravisCI. I'll run the tests locally. I think these changes look great, I'll merge them in today, scan the Dark Sky API docs for any additions, and cut a release tonight. Thanks for your contribution, and my apologies again for letting this get so stale.

**Comment by ParadoxSpiral** [comment]
Thanks!
I've had, and have seen quite a few people, with the same e-mail notification problem. Rather curious.

**Comment by jgrillo** [comment]
@ParadoxSpiral I merged your changes, did a little bit of hacking on the integration tests, and updated some things to get up to par with the most recent Dark Sky API (why don't they have versions?). I also published a 1.0.0 crate. Feel free to submit further PRs or open an issue if any of these changes don't work for you, I've fixed the notifications issue and I promise I'll respond more quickly next time!

**Pull request merged**
